# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
    # PLUGINS
    # Mount Plugin
    { on = "M", run = "plugin mount" },
    #toggle-pane-plugin
    { on = [
        "b",
        "b",
    ], run = "plugin toggle-pane max-preview", desc = "max preview" },
    { on = [
        "b",
        "n",
    ], run = "plugin toggle-pane min-preview", desc = "hide preview" },
    #system-clipboard Plugin
    { on = [
        "c",
        "y",
    ], run = "plugin system-clipboard", desc = "yank to clipboard" },
    #Plugin relative-motions (gt bei tabs) (https://github.com/dedukun/relative-motions.yazi)
    { on = "1", run = "plugin relative-motions 1", desc = "Move in relative steps" },
    { on = "2", run = "plugin relative-motions 2", desc = "Move in relative steps" },
    { on = "3", run = "plugin relative-motions 3", desc = "Move in relative steps" },
    { on = "4", run = "plugin relative-motions 4", desc = "Move in relative steps" },
    { on = "5", run = "plugin relative-motions 5", desc = "Move in relative steps" },
    { on = "6", run = "plugin relative-motions 6", desc = "Move in relative steps" },
    { on = "7", run = "plugin relative-motions 7", desc = "Move in relative steps" },
    { on = "8", run = "plugin relative-motions 8", desc = "Move in relative steps" },
    { on = "9", run = "plugin relative-motions 9", desc = "Move in relative steps" },

    #CUSTOM KEYBINDS

    #macos preview nutzen
    { on = "<C-p>", run = 'shell -- qlmanage -p "$@"', desc = "Macos preview" },
    # g-r bringt einen ins root vom git rep
    { on = [
        "g",
        "r",
    ], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "root git" },

    # Operation
    { on = "o", run = "open --interactive", desc = "Open selected files interactively" },
    { on = "O", run = "open", desc = "Open selected files" },
    { on = [
        "g",
        "<Space>",
    ], run = "plugin zoxide", desc = "zoxide (dir)" },
    { on = [
        "g",
        "f",
    ], run = "plugin fzf", desc = "fzf (file and dir)" },

    # Copy
    { on = [
        "c",
        "c",
    ], run = 'osascript -e "set the clipboard to (POSIX file \"$PWD/$1\")"', desc = "Copy path" },
    { on = [
        "c",
        "s",
    ], run = "copy path", desc = "Copy path as string" },
    { on = [
        "c",
        "d",
    ], run = "copy dirname", desc = "Copy dir path" },
    { on = [
        "c",
        "f",
    ], run = "copy filename", desc = "Copy name" },
    { on = [
        "c",
        "n",
    ], run = "copy name_without_ext", desc = "name w/o extension" },


    # Goto
    { on = [
        "g",
        "h",
    ], run = "cd ~", desc = "goto Home" },
    { on = [
        "g",
        "c",
    ], run = "cd ~/dotties", desc = "goto dotfiles" },
    { on = [
        "g",
        "d",
    ], run = "cd ~/Downloads", desc = "goto Downloads" },
    { on = [
        "g",
        "i",
    ], run = "cd --interactive", desc = "Jump interactively" },
    { on = [
        "g",
        "s",
    ], run = "cd ~/Developer/4SoSe25", desc = "goto Semeseter" },
    { on = [
        "g",
        "v",
    ], run = "cd /Volumes", desc = "goto Volumes" },
    { on = [
        "g",
        "m",
    ], run = "cd ~/Movies", desc = "goto Movies" },
    { on = [
        "g",
        "p",
    ], run = "cd ~/Pictures", desc = "goto Pictures" },
]
