[flavor]
light = "catppuccin-latte"
#dark = "catppuccin-frappe"
#dark = "dracula"
#dark = "ayu-dark"
#dark = "kanagawa"
#ark = "catppuccin-mocha"
dark = "catppuccin-macchiato"
#dark = "everforest-medium"
